### ISSUE TITLE
Error when connecting to PKI enabled server

### ISSUE THREAD

**Issue by hamiltoncj** [QGIS-Contribution/QGIS-ResourceSharing#169]
When I attempt to add a repository to a server that uses PKI authentication. I click on the "Add..." button and give it a name and url, then next to Authentication I click on Add to select my certificate token then click on "OK", I get this error message:

type object 'QgsAuthManager' has no attribute 'instance'

**Comment by hamiltoncj** [comment]
This error occurs in network_manager.py and probably at line #56 with these lines of code:
QgsAuthManager.instance().updateNetworkRequest(
                request, self._auth_cfg
            )
I have been using QgsNetworkContentFetcher for these calls and it works beautifully because auth_cfg is integrated into it. The only problem is that it requires QGIS 3.10 and above. QgsBlockingNetworkRequest also works well and works with QGIS 3.6 and above. I made some attempt to fix the problem, but am not sure how to do it with a QNetworkRequest.

**Comment by zacharlie** [comment]
I also got the `type object 'QgsAuthManager' has no attribute 'instance'` error when trying to use the authentication manager.

@ricardogsilva pointed out to me that `QgsApplication.authManager()` is the correct way to instantiate the authentication manager.

I had a look and it seems the API changed. I have a draft pull request #170 which seemed to fix this for me but I think needs further testing.

**Comment by hamiltoncj** [comment]
I have already tried this as a fix, but it is not sufficient. PKI authentication is quite complex and I tried at one time to implement it with QNetworkRequest, but there is much more to it then this. I never really got it working. The QGIS team put a lot of work into QgsNetworkContentFetcher and QgsBlockingNetworkRequest  and made sure they work with PKI. I don't recommend that you use QNetworkRequest because it is going to continually cause problems. I recommend that you switch to one of these QGIS integrated calls.

**Comment by hamiltoncj** [comment]
I have one other comment which is that QgsApplication.authManager() fixed the error I first reported, but it does not fix the PKI authentication. What fails now is the SSL handshake.

**Comment by hamiltoncj** [comment]
@zacharlie 
I have been doing some more testing, using 

QgsApplication.authManager().updateNetworkRequest(
    request, self._auth_cfg
)

fixes this main problem and allows the directory of resources to be read; however, it appears that that the auth_cfg id is not being used when the actual resource is requested which results in an SSL error to download the resource.
